### ISSUE TITLE
The "Open Editor" button is missing on the Delight panel

### ISSUE THREAD

**Issue by Fernando-Marquardt** [delight-dev/Delight#21]
I am using the Delight asset available on Asset Store and could not make the "Open Designer" button to show on the Delight window (I have enabled TextMeshPro, rebuilt all and even restarted Unity).

So I took a look at the source code and found that the "Open Designer" button is commented out. I uncommented the code and had to change "DelightDesigner.unity" location to the "Content" folder inside the asset.

**Comment by patrik-u** [comment]
Thank you Fernando, I forgot about the button as I've been opening the scene manually. I've made the change. Also added:

`EditorApplication.isPlaying = true;`

After OpenScene() to play the scene when the button is pressed.
