### ISSUE TITLE
Enable Label in dinamically created Button

### ISSUE THREAD

**Issue by pabloHoc** [delight-dev/Delight#24]
Hi! First of all, I want to thank you for making this tool, I'm still learning how to use it but it seems really helpful so far. 

Now to my problem. I'm trying to create a button dinamically, but I couldn't find the way to activate the label's button. The label is always disabled, and it doesn't have any text. Other things I tried: 

- accesing Label properties directly, e.g.: `button.Label.IsActive`
- accesing the label's `GameObject`, e.g.: `button.Label.GameObject.SetIsActive(true)`

I'm not even sure if I'm doing it in the right method (should it be `BeforeInitialize`? `BeforeLoad`?). I'm using TextMesh Pro, btw.

This is my current code. Thanks a lot!

```C#
namespace Delight
{
  public partial class MyPanel
  {
    public override void AfterInitialize()
    {
      var buttonGroup = this.Find<Group>("Buttons");

      new Button(buttonGroup, buttonGroup, "CloseButton")
      {
        Text = "Close",
        DisplayLabel = true,
        LabelIsActive = true,
        Width = ElementSize.FromPercents(1),
        Height = ElementSize.FromPixels(100),
        Alignment = ElementAlignment.Bottom
      };

      base.AfterInitialize();
    }
  }
}
```

**Comment by patrik-u** [comment]
The problem in this case is that the property Button.Text maps to Button.Label.TextMeshProUGUI.text, and the TextMeshProUGUI component is created first during loading of the label view. So in your case what you need to do is create the button in AfterLoad, load the button, and then set the properties:

```cs
        protected override void AfterLoad()
        {
            base.AfterLoad();
            var button = new Button(Buttons, Buttons, "CloseButton"); 
            button.Load(); 
            button.Text = "Close"; 
            // etc.
        }
```

**Comment by pabloHoc** [comment]
Ah, it makes sense. Thanks a lot, it works now!
