### ISSUE TITLE
Using Layout Groups

### ISSUE THREAD

**Issue by pabloHoc** [delight-dev/Delight#26]
Could it be possible to add Layout Groups and Layout Elements as components to some custom views, and setting their properties using XML? And extend some default views to have Layout Elements properties (like Buttons)? I'm think in an API something like

```xml
<VerticalGroup forceExpandWidth="false">
  <Button flexibleHeight="1" />
  <Button flexibleHeight="2" />
</VerticalGroup>
```

If it is feasible, where I could start? I don't mind doing extra work if it is necessary, but I would appreciate a lot some direction, examples or ideas. 

Thanks a lot!

**Comment by patrik-u** [comment]
The section in the Views tutorial explains perhaps what you want to do. It shows how to add components to your custom views: 
[https://delight-dev.github.io/Tutorials/Views.html#mapped-dependency-properties](https://delight-dev.github.io/Tutorials/Views.html#mapped-dependency-properties)

So if you create a custom VerticalGroup view you can add the Vertical Layout Group component similar to how the shadow component is added in the tutorial. And you need to create the component in code-behind as shown in the tutorial as well. 

To implement setting the layout element on Button I recommend using attached properties, so the result will be something like: 

```
<VerticalGroup ForceExpandWidth="false">
  <Button VerticalGroup.FlexibleHeight="1" />
  <Button VerticalGroup.FlexibleHeight="2" />
</VerticalGroup>
```

The tutorial on attached properties is here:
[https://delight-dev.github.io/Tutorials/Views.html#attached-properties](https://delight-dev.github.io/Tutorials/Views.html#attached-properties)

The attached properties is added to your custom vertical group, and you need to implement some logic in your code-behind of VerticalGroup that checks if a attached property is set (you can do this in AfterLoad) - then add the layout element component it to the attached child view and set the attached property on it.

**Comment by patrik-u** [comment]
If you don't want to use attached properties, another possibility is to extend UIView and add the Layout Element properties to it. And in the code-behind add functionality to add the Layout Element component to the view if any of those properties are set (you don't want to add the component unless it's used as it will increase the load time and memory usage a lot if the component isn't used). Then you can set the properties like your example:

```
<VerticalGroup forceExpandWidth="false">
  <Button FlexibleHeight="1" />
  <Button FlexibleHeight="2" />
</VerticalGroup>
```

**Comment by pabloHoc** [comment]
Great! I like the second solution more too, I'm gonna give it a try. It doesn't sound so hard. Thanks a lot! I let you know if I hit some wall.
