### ISSUE TITLE
Moving entire Delight into Assets subfolder and changing DelightPath in config.txt results in IO exceptions

### ISSUE THREAD

**Issue by Shelim** [delight-dev/Delight#28]
Hello!

First and foremost: thanks for the wonderful tool - I was about to implement something very similar by myself, until I stumbled to your solution :-)

For the bug:

# Steps to reproduce:

1. Download `Delight-latest.unitypackage` and open it in Unity 2020.1.10f1 (did not try other versions)
2. Move `Delight` folder -> `3rdParty\Delight\Delight`
3. Move `Content` folder -> `3rdParty\Delight\Content`
4. Create `Game/Delight` folder for custom content
5. Change `config.txt`:
```
ServerUri: http://example.com
UseSimulatedUriInEditor: true
BuildTargets: Dev
AssetBundleVersion: 1
DelightPath: 3rdParty/Delight/ 
ContentFolders:
	Game/Delight/
	3rdParty/Delight/Content/ 
DefaultContentFolder: Game/Delight/
Modules: 
  TextMeshPro
```

# Expected behaviour:

The config should be read properly

# Observed behaviour:

On each asset change:
 - `DirectoryNotFoundException: Could not find a part of the path "D:\MyProject\Assets\Delight\Content\Config_g.cs".`
 - `FileNotFoundException: Could not find file "D:\MyProject\DelightConfig.bin"`

The problem persist even after restarting Unity (I saw a few static fields for config)

**Comment by patrik-u** [comment]
Thanks for your bug report Shelim.

**Comment by aornelas** [comment]
hi! are there any workarounds for this? i'm using Delight for a sample implementation of our SDK, so it gets distributed as a unitypackage that our users then integrate into their own projects; as such, having top-level directories is kind of a deal breaker... any workaround to encapsulate all of the Delight code into a subdirectory would be greatly appreciated!

**Comment by patrik-u** [comment]
No known workarounds currently. You might try delving in the code-base.. as it's open-source you could attempt fix the issue, to make it so e.g. default folder to be configured e.g. through a project setting. Right now the config file need to reside where it is in the content folder, as the path is hard-coded.

**Comment by aornelas** [comment]
thanks for the suggestion, Patrik!

took a stab at it and managed to get it working by identifying and updating all the relevant hardcoded paths after you move Delight into a subdirectory.

...documenting here in case others are interested in this manual workaround and for bug-fixing reference:

_Assets/SUB_DIR/Delight/Source/Editor/DelightControlPanel.cs:99_
```
                    EditorSceneManager.OpenScene("Assets/SUB_DIR/Delight/Content/Scenes/DelightDesigner.unity");
```

_Assets/SUB_DIR/Delight/Source/Editor/Parser/MasterConfig.cs:292_
```
            var rootPrefix = "Assets/SUB_DIR/";
            ContentFolders.Add(rootPrefix + "/Content/");
            ContentFolders.Add(rootPrefix + "/DelightDevContent/");
            ContentFolders.Add(rootPrefix + "/Delight/Content/");
            ContentFolders.Add(rootPrefix + "/Plugins/Content/");
            ContentFolders.Add(rootPrefix + "/Plugins/Delight/Content/");
```

_Assets/SUB_DIR/Delight/Source/Editor/Parser/MasterConfig.cs:323_
```
                    string contentFolder = String.Format("Assets/SUB_DIR/Delight/Extensions/{0}/", directoryName);
```

**Comment by patrik-u** [comment]
Thanks for your fix, added it to the codebase. There is now a static field "DefaultDirectory" in the MasterConfig class, for an easy way to change the root folder until a more robust solution is in place that doesn't require modifying the source. 

```csharp
    public class MasterConfig
    {
        public static string DefaultDirectory = "/"; // edit the following string to add Delight framework into a default subfolder, e.g. "SUB_DIR/"
```

**Comment by aornelas** [comment]
thank you for taking caring of this!
