### ISSUE TITLE
Background sprite not resizing correctly in Frame/Group ?

### ISSUE THREAD

**Issue by nicokruger** [delight-dev/Delight#29]
Hi there,

Maybe a misunderstanding on my part, but just want to clarify. I'm trying to make a Frame (or a Group) that resizes automatically to its content. According to the docs, it seems like the Frame component is meant for this.

```
<Frame Margin="0"
       BackgroundSprite="BlueBackground"
  >
    <Label AutoSize="Width" Text="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasdfasaadddddsdssdgdsfgsdfgsdfg" FontColor="White" Alignment="Top"/>
</Frame>
```

So I want the Frame to resize according to the content inside of it. This seems to be working, however, the background sprite is not being resized.

If I use a Group:
```
<Group Margin="0"
       BackgroundSprite="BlueBackground"
       BackgroundType="Sliced"
  >
    <Label AutoSize="Width" Text="daaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasdfasaadddddsdssdgdsfgsdfgsdfg" FontColor="White" Alignment="Top"/>
</Group>
```
It seems to be resizing the Group as well, but in this case the background image is stretched and not sliced.

Am I missing something? The only way I can get the frame to resize correctly with its background sprite is to explicitly set the width and height.

**Comment by patrik-u** [comment]
Hey, thanks for that bug-report. I believe it was because the view resizes to native size of sprite when width/height not set. This is unintended behavior (except for the Image view which should behave like that). Checked in a fix:

https://github.com/delight-dev/Delight/commit/1e12c66a8ade83ba2ec6dcd6fa049715d0a728ac

**Comment by nicokruger** [comment]
Awesome, thanks for the quick feedback!

I've patched it on my end and it looks to now be using the Frame size and not native size.

Thanks for an awesome framework!
