### ISSUE TITLE
Any way to declare and reuse colours by name?

### ISSUE THREAD

**Issue by Lancelotbronner** [delight-dev/Delight#33]
In the XML, I tried "#ffffffde" but it seems to ignore the first two characters and sets the "de" to the B component.

On a close note, are there any way to declare colours to then reuse them by name? That would be very helpful.

Thanks in advance! Love your framework!

**Comment by Lancelotbronner** [comment]
I had a flash that ARGB is a thing and indeed that was the issue, I'll leave this however for the reusing colours by name because I would love that!

**Comment by patrik-u** [comment]
Yes :). Reusing colors by name is a good idea and it's in my TODO. There is
a way to do it currently through bindings, but you have to declare it in
code. So you can do:

```
namespace Delight
{
    public static partial class Models
    {
        public static Color MyColor = new Color(...);
    }
}
```

```
<Region BackgroundColor="{@MyColor}" />
```

Den fre 29 jan. 2021 kl 05:13 skrev Lancelotbronner <
notifications@github.com>:

**Comment by Lancelotbronner** [comment]
Thanks, that makes a lot of sense, I don’t know why I didn’t think of that!
