### ISSUE TITLE
No asset store?

### ISSUE THREAD

**Issue by sommmen** [delight-dev/Delight#4]
Hi,

Any reason to why this is not in the asset store?

**Comment by patrik-u** [comment]
Hi, it was declined due to the project's folder-structure and lack of
documentation, and I just couldn't be bothered getting it through the
approval process.


Den lör 14 mars 2020 kl 19:59 skrev sommmen <notifications@github.com>:

**Comment by sommmen** [comment]
Okay i was just wondering :)
