### ISSUE TITLE
minor issue including Scene assets in application resources

### ISSUE THREAD

**Issue by dmacd** [delight-dev/Delight#40]
I accidentally included some demo scenes from a plugin in the Content/Assets folder. This lead to the generation of this code in `Assets_g.cs` which breaks at build time due to missing UnityEditor namespace, though it runs fine in the editor. Not blocking for me as I didnt' need these scene assets but was a little confusing to track down.

```
    #region SceneAssets

    /// <summary>
    /// Manages a UnityEditor.SceneAsset object. Loads/unloads the asset on-demand as it's requested by views.
    /// </summary>
    public partial class SceneAsset : AssetObject<UnityEditor.SceneAsset>
    {
        public static implicit operator SceneAsset(UnityEditor.SceneAsset unityObject)
        {
            return new SceneAsset { UnityObject = unityObject, IsUnmanaged = true };
        }

        public static implicit operator SceneAsset(string assetId)
        {
            if (String.IsNullOrEmpty(assetId))
                return null;

            if (assetId.StartsWith("?"))
                assetId = assetId.Substring(1);

            return Assets.SceneAssets[assetId];
        }
    }
```

**Comment by patrik-u** [comment]
Thanks for the bug report, I'll make a note of the issue and see if I can add some checks in the code generation so it doesn't happen.

**Comment by dmacd** [comment]
Update: I originally thought this was a minor issue but for some reason this chunk of code gets regenerated every time I try to build or switch build targets, so I cant easily build my project anymore.

 I've removed the original, offending scenes from the Content/Assets folder, but something is still cached somewhere. Any hints on where the stale state might be lurking?

**Comment by patrik-u** [comment]
> Update: I originally thought this was a minor issue but for some reason this chunk of code gets regenerated every time I try to build or switch build targets, so I cant easily build my project anymore.
> 
> I've removed the original, offending scenes from the Content/Assets folder, but something is still cached somewhere. Any hints on where the stale state might be lurking?

You could try pressing "Rebuild all" in the delight window and see if the cached data is cleared. If not you might have to delete the files "DelightConfig.bin" and "DelightContent.bin" that contains the state. Let me know if it works.

**Comment by dmacd** [comment]
Unfortunately that didn't work. As soon as I switch to another build target, the evil code comes back :( 
Anything else I can try?

**Comment by patrik-u** [comment]
For a quick fix you could try modify the code generation to ignore everything from the Editor namespace. You should find the code in the `CodeGenerator.cs` do a search for `: AssetObject<` for the code that generates it. I'll have a chance to look at this in the weekend.

**Comment by dmacd** [comment]
Thanks. This did the trick
```
            // generate asset object data
            List<UnityAssetObject> assetObjects = _contentObjectModel.AssetBundleObjects.SelectMany(x => x.AssetObjects).ToList();
            foreach (var assetType in _contentObjectModel.AssetTypes)
            {
                if (assetType.Name == "DefaultAsset")
                    continue; // ignore default assets

                // DJM HACK 
                if (assetType.FullName.Contains("UnityEditor."))
                    continue; // ignore editor assets
                    
                ...   
```

**Comment by patrik-u** [comment]
> Thanks!! This did the trick

Awesome, thank you for the fix :).

**Comment by patrik-u** [comment]
Added fix to master-branch.
